apiDebug: false
timeout: 20000
contractsPath: ../contracts/
multiNode: false
deploymentDelay: 1000


# WARNING - extra strict syntax
# DO NOT change the nodes order
# node 0 is the default url for all single node api calls
nodes:
  - id: 0
    blocUrl: 'http://0.0.0.0:8000'
    explorerUrl: 'http://tester7.centralus.cloudapp.azure.com/explorer'
    stratoUrl: 'http://tester7.centralus.cloudapp.azure.com/strato-api'
#    blocUrl: 'http://tester7.centralus.cloudapp.azure.com/bloc'
    searchUrl: 'http://tester7.centralus.cloudapp.azure.com/cirrus'
